module.exports = [
    {
        str:"Mécanicien(voir Garagiste)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Médecin",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Messagerie espress(Entreprise de)",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Meublé(Loueur en) non titulaire de licence",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Meublé(Loueur en) non titulaire de licence - disposant de plus de 10 pièces",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str:"Meublé(Loueur en) non titulaire de licence - disposant de 10 pièces et moins",
        lbv_pog:15000,
        autre_commune:15000,
        departement:12000,
    },
    {
        str:"Meubles Fabricant de (voir Atelier pour les TV)",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Meubles(Loueur de)",
        lbv_pog:24000,
        autre_commune:24000,
        departement:18000,
    },
    {
        str:"Navigation aérienne(Compagnie de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Navigation aérienne(Compagnie de) - établissement principal du territoire",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Navigation aérienne(Compagnie de) - établissement secondaire du territoire",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Navigation fluviale(Compagnie de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Navigation fluviale(Compagnie de) - établissement principal du territoire",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Navigation fluviale(Compagnie de) - établissement secondaire du territoire",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Navigation maritime(Compagnie de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Navigation maritime(Compagnie de) - établissement principal du territoire",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Navigation maritime(Compagnie de) - établissement secondaire du territoire",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Navires(voir Consignataire)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Notaire",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Notaire - employant plus d'une personne",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Notaire - employant une personne",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Notaire - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Opticien - lunetier",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Orfèvre(voir Bijoutier)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Orthophoniste",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Papetier(voir Librairie)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Pâtissier",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Paysagiste, entrepreneur de jardins",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Pédicure(voir Coiffeur pour dames pour les TV)",
        lbv_pog:60000,
        autre_commune:60000,
        departement:50000,
    },
    {
        str:"Peintre en bâtiment(voir Artisan)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Pharmacien",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Pharmacien - importateur",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Pharmacien - n'important pas",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
]