module.exports = [
    {
        str:"Transports terrestres sociétés(Entrepreneur de)",
        lbv_pog:70000,
        autre_commune:70000,
        departement:70000,
    },
    {
        str:"Transports terrestres sociétés(Entrepreneur de) - par place des autocars ou taxi-bus",
        lbv_pog:70000,
        autre_commune:70000,
        departement:70000,
    },
    {
        str:"Transports terrestres sociétés(Entrepreneur de) - âr tonne de charge utile des camions, camionnettes ou remorques",
        lbv_pog:70000,
        autre_commune:70000,
        departement:70000,
    },
    {
        str:"Travaux(Entrepreneur de)",
        lbv_pog:120000,
        autre_commune:120000,
        departement:120000,
    },
    {
        str:"Travaux(Entrepreneur de) - par cheval-vapeur du matériel utilisé(véhicules moteurs,etc)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Travaux(Entrepreneur de) - par personne employée",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Travaux(Entrepreneur de) - par personne employée en sus de 20",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Usine(Exploitant une), ( voir Atelier pour les TV)",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Vannier",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str:"Véhicules(Laveurs de)",
        lbv_pog:40000,
        autre_commune:40000,
        departement:40000,
    },
    {
        str:"Véhicules d'occasion",
        lbv_pog:170000,
        autre_commune:170000,
        departement:100000,
    },
    {
        str:"Véhicules(Loueur de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"1)Utilitaires(sociétés)",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str:"1)Utilitaires(sociétés) - par véhicule loué",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"2)Utilitaires(particuliers)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"2)Utilitaires(particuliers) - par camion et par an",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"2)Utilitaires(particuliers) - par tonne et par an",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"3)De tourisme(particulier ou société)",
        lbv_pog:70000,
        autre_commune:70000,
        departement:60000,
    },
    {
        str:"De tourisme(particulier ou société) - par véhicule loué",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Vendeurs de produits du cru, y compris le cacao, sans établissement fixe, (en tant que vendeurde produitde crû) dans la commune ou le département(patente établie par commune ou département)",
        lbv_pog:35000,
        autre_commune:35000,
        departement:15000,
    },
    {
        str:"Vétérinaire",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Vidange(Entreprise de)",
        lbv_pog:70000,
        autre_commune:70000,
        departement:70000,
    },
    {
        str:"Voyage(Agent de) par véhicule",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Voyage(Agent de) par véhicule - employant plus d'une personne",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Voyage(Agent de) par véhicule - employant une personne",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Voyage(Agent de) par véhicule - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
]