module.exports = [
    {
        str: "Avocat ou Avocat défenseur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Avocat ou Avocat défenseur - employant plus d'un secrétaire, ayant une qualité pour plaider",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Avocat ou Avocat défenseur - employant un secrétaire, ayant qualité pour plaider",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Avocat ou Avocat défenseur - n'employant aucun secrétaire, ayant une qualité pour plaider",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Avoué",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Avoué - employant plus d'une personne",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Avoué - employant une personne",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Banque",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Avoué - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Banque - établissement principal du territoire",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str: "Banque - établissement secondaire du territoire",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str: "Bétail(Exportateur de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Bétail(Exportateur de) - exportant annuellement plus de 200 têtes",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Bétail(Exportateur de) - exportant annuellement plus de 100 têtes",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str: "Bétail(Exportateur de) - exportant annuellement moins de 100 têtes",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str: "Bétail(Marchand de)",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str: "Biens immobiliers(Entreprise se livrant à l'achat, la vente, l'échange de biens immobiliers ou à toute autre spéculation analogue",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Bijoutier - Horloger",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Bijoutier - Horloger - vendant des objets importés par lui",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Bijoutier - Horloger - vendant des objets non fabriqués par lui et n'important pas",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Bijoutier - Horloger - vendant des objets fabriqués par lui et n'important pas",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str: "Blanchisseur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Blanchisseur - travaillant seul",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str: "Blanchisseur - employant 1 à 5 personnes",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str: "Bois(Exportateur de commissionnaire en)",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Bois de chauffe ou chauffage(Marchand de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Bois de chauffe ou chauffage(Marchand de) - vendant ) des clients autres que des bateaux de passage",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str: "Bois de chauffe ou de chauffage(Marchand de) - ne vendant qu'à des bateaux de passage",
        lbv_pog:24000,
        autre_commune:24000,
        departement:18000,
    },
    {
        str: "Bois de chauffe ou de chauffage(Marchand de) - vendant au petit détail",
        lbv_pog:15000,
        autre_commune:15000,
        departement:12000,
    },
    {
        str: "Boissons locales(fabricant de)",
        lbv_pog:15000,
        autre_commune:15000,
        departement:12000,
    },
]