module.exports = [
    {
        str:"Gardiennage et surveillance(Entreprise de)",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Géomètre: par employé",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Géomètre: par employé - employant plus de 4 personnes",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Géomètre: par employé - employant 3 ou 4 personnes",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Géomètre: par employé - employant moins de 3 personnes",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Guide de chasse",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Horloger(voir Bijoutier)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Hôtel non titulaire d'une licence",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Hôtel non titulaire d'une licence - disposant de plus de 10 chambres",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Hôtel non titulaire d'une licence - disposant de moins de 10 chambres",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Hôtel titulaire d'une licence de 1 ère classe",
        lbv_pog:260000,
        autre_commune:130000,
        departement:100000,
    },
    {
        str:"Hôtel titulaire d'une licence de 1 ère classe - comprenant plus de 100 chambres",
        lbv_pog:190000,
        autre_commune:95000,
        departement:80000,
    },
    {
        str:"Hôtel titulaire d'une licence de 1 ère classe - comprenant entre 50 et 100 chambres",
        lbv_pog:160000,
        autre_commune:80000,
        departement:65000,
    },
    {
        str:"Hôtel titulaire d'une licence de 1 ère classe - comprenant entre 20 et 49 chambres",
        lbv_pog:100000,
        autre_commune:55000,
        departement:40000,
    },
    {
        str:"Hôtel titulaire d'une licence de 1 ère classe - comprenant moins de 20 chambres",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 1) Faisant dancing",
        lbv_pog:540000,
        autre_commune:260000,
        departement:200000,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 1) Faisant dancing - comprenant plus de 100 chambres",
        lbv_pog:450000,
        autre_commune:225000,
        departement:180000,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 1) Faisant dancing - comprenant entre 50 et 100 chambres",
        lbv_pog:400000,
        autre_commune:200000,
        departement:160000,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 1) Faisant dancing - comprenant entre 20 et 49 chambres",
        lbv_pog:320000,
        autre_commune:170000,
        departement:145000,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 1) Faisant dancing - comprenant moins de 20 chambres",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 2) Ne faisant pas dancing",
        lbv_pog:440000,
        autre_commune:220000,
        departement:170000,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 2) Ne faisant pas dancing - comprenant plus de 100 chambres",
        lbv_pog:360000,
        autre_commune:180000,
        departement:160000,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 2) Ne faisant pas dancing - comprenant entre 50 et 100 chambres",
        lbv_pog:300000,
        autre_commune:160000,
        departement:130000,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 2) Ne faisant pas dancing - comprenant entre 20 et 49 chambres",
        lbv_pog:250000,
        autre_commune:125000,
        departement:100000,
    },
    {
        str:"Hôtel-café-restaurant, titulaire d'une licence de 1 ère classe - 2) Ne faisant pas dancing - comprenant moins de 20 chambres",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Huissier",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Importateur ou exportateur, dont le montant des importations, dont le montant des importations taxées par bureau de douane est:",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Importateur ou exportateur, dont le montant des importations, dont le montant des importations taxées par bureau de douane est: - supérieur à 100 millions",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Importateur ou exportateur, dont le montant des importations, dont le montant des importations taxées par bureau de douane est: - compris entre 50 et 100 millions",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Importateur ou exportateur, dont le montant des importations, dont le montant des importations taxées par bureau de douane est: - Inférieur à 50 millions",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
]