module.exports = [
    {
        str:"Crédit-ball mobilier ou immobilier",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Crédit-ball mobilier ou immobilier - établissement principal du territoire",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Crédit-ball mobilier ou immobilier",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Culture physique(Salle de)",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Cybercafé",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Cybercafé - 1 à 3 appareils(par appareil)",
        lbv_pog:110000,
        autre_commune:110000,
        departement:80000,
    },
    {
        str:"Cybercafé - plus de 3 appareils",
        lbv_pog:110000,
        autre_commune:110000,
        departement:80000,
    },
    {
        str:"Dancing",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Dancing - faisant dancing",
        lbv_pog:260000,
        autre_commune:130000,
        departement:95000,
    },
    {
        str:"Dancing - ne faisant pas dancing",
        lbv_pog:160000,
        autre_commune:80000,
        departement:65000,
    },
    {
        str:"Débardage(voir Entreprise de travaux pour les TV)",
        lbv_pog:120000,
        autre_commune:120000,
        departement:120000,
    },

    {
        str:"Déménagement(Exploitant une entreprise de)",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Dentiste",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Déroulage(Usine de)(Voir Commerçant)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Détail(Magasin de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Détail(Magasin de) - en vrac et ambulant",
        lbv_pog:60000,
        autre_commune:60000,
        departement:40000,
    },
    {
        str:"Détail(Magasin de) - épicerie",
        lbv_pog:65000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str:"Détail(Magasin de) - prêt à porter",
        lbv_pog:100000,
        autre_commune:65000,
        departement:65000,
    },
    {
        str:"Détail(Magasin de) - produit de beauté",
        lbv_pog:100000,
        autre_commune:65000,
        departement:65000,
    },
    {
        str:"Détail(Magasin de) - par personne employée",
        lbv_pog:100000,
        autre_commune:65000,
        departement:65000,
    },
    {
        str:"Détail(Magasin de) - par personne employée en sus de 5",
        lbv_pog:100000,
        autre_commune:65000,
        departement:65000,
    },
    {
        str:"Eau et énergie électrique(Production et exploitation d'un réseau de distribution de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Eau et énergie électrique(Production et exploitation d'un réseau de distribution de) - agglomération de plus de 50.000 habitants",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Eau et énergie électrique(Production et exploitation d'un réseau de distribution de) - agglomération de 30.000 à 50.000 habitants",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Eau et énergie électrique(Production et exploitation d'un réseau de distribution de) - agglomération de 10.000 à 30.000 habitants",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Eau et énergie électrique(Production et exploitation d'un réseau de distribution de) - agglomération de moins de 10.000 habitants",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Ecailleur de poissons",
        lbv_pog:20000,
        autre_commune:15000,
        departement:15000,
    },
    {
        str:"Ecole de danse comptabilité, dactylographie, mécanographie(Tenant une)",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Ecole de danse gymnastique culture physique(Tenant une)",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Ecrivain public",
        lbv_pog:15000,
        autre_commune:15000,
        departement:12000,
    },
    {
        str:"Editeur",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Energie électrique(voir Eau)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Energie électrique - agglomération de plus de 50.000 habitants",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Energie électrique - agglomération de 30.000 à 50.000 habitants",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Energie électrique - agglomération de 10.000 à 30.000 habitants",
        lbv_pog:170000,
        autre_commune:170000,
        departement:110000,
    },
    {
        str:"Energie électrique - agglomération de moins de 10.000 habitants",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Enseignement à but lucratif(Etablissement de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Enseignement à but lucratif(Etablissement de) - recevant des élèves pensionnaires",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Enseignement à but lucratif(Etablissement de) - recevant des élèves demi-pensionnaires",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Enseignement à but lucratif(Etablissement de) - recevant des élèves externes",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Entrepôt(Concessionnaire d')",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Esthéticienne",
        lbv_pog:60000,
        autre_commune:60000,
        departement:50000,
    },
    {
        str:"Esthéticienne - par personne employée",
        lbv_pog:60000,
        autre_commune:60000,
        departement:50000,
    },
    {
        str:"Esthéticienne - par personne employée en sus de 4",
        lbv_pog:60000,
        autre_commune:60000,
        departement:50000,
    },
    {
        str:"Etudes(Tenant un bureau)",
        lbv_pog:60000,
        autre_commune:60000,
        departement:50000,
    },
]