module.exports = [
    {
        str:"Exécution(Agent d')",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Expertise automobile(Tenant un cabinet)",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Expert-comptable ou Réviseur comptable",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Expert-comptable ou Réviseur comptable - employant plus d'une personne",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Expert-comptable ou Réviseur comptable - employant une personne",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Expert-comptable ou Réviseur comptable - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Expertise comptable(Société d')",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Expertise comptable - établissement principal de territoire",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Expertise comptable - établissement secondaire du territoire",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Expertise maritime(tenant un cabinat)",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Exportateur",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Exportateur - supérieur à 100 millions",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Exportateur - Compris entre 50 et 100 millions",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Exportateur - Inférieur à 50 millions",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Fabrique(Exploitant une)",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Fabrique(Exploitant une) - par CV de matériel utilisé, non compris les véhicules",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Fabrique(Exploitant une) - par personne employée",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Fabrique(Exploitant une) - par personne employée",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Ferraille(Marchand de)",
        lbv_pog:120000,
        autre_commune:120000,
        departement:120000,
    },
    {
        str:"Fleuriste importateur",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Fonds de commerce, installations industrielles ou commerciales(Loueur de)",
        lbv_pog:85000,
        autre_commune:85000,
        departement:85000,
    },
    {
        str:"Forage pétrolier(Entreprise de)",
        lbv_pog:100000,
        autre_commune:100000,
        departement:100000,
    },
    {
        str:"Forage pétrolier(Entreprise de) - par plateforme",
        lbv_pog:100000,
        autre_commune:100000,
        departement:100000,
    },
    {
        str:"Forestier(Exploitant) réalisant par chantier:",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Forestier(Exploitant) réalisant par chantier: - un chiffre d'affaires annuel supérieur à 250 millions",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Forestier(Exploitant) réalisant par chantier: - un chiffre d'affaires annuel compris entre 100 et 250 millions",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str:"Forestier(Exploitant) réalisant par chantier: - un chiffre d'affaires annuel compris entre 50 et 100 millions",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Forestier(Exploitant) réalisant par chantier: - un chiffre d'affaires annuel compris entre 20 et 50 millions",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Forestier(Exploitant) réalisant par chantier: - un chiffre d'affaire annuel compris entre 5 et 20 millions",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Forestier(Exploitant) réalisant par chantier: - un chiffre d'affaires annuel inférieur à 5 millions",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Fripier",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str:"Garagiste ou mécanicien",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Garagiste ou mécanicien - important uniquement les pièces détachées produits nécessaires aux réparations",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Garagiste ou mécanicien - n'important pas",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str:"Garderie d'enfants",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
]