module.exports = [
    {
        str:"Marchand ambulant",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Marchandambulant - 1)Sur bateau, embarcation ou pinasse à vapeur, moteur ou voile(a)",
        lbv_pog:30000,
        autre_commune:30000,
        departement:30000,
    },
    {
        str:"Marchandambulant - 1)Sur bateau, embarcation ou pinasse à vapeur, moteur ou voile(a) - par bateau, embarcation ou pinasse",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"2)Avec camion automobile(a)",
        lbv_pog:30000,
        autre_commune:30000,
        departement:30000,
    },
    {
        str:"2)Avec camion automobile(a) - par camion ou remorque",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"3)Avec voiture automobile(a)",
        lbv_pog:25000,
        autre_commune:25000,
        departement:18000,
    },
    {
        str:"3)Avec voiture automobile(a) - par voiture ou remorque",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"4)Sur pirogue(a)",
        lbv_pog:18000,
        autre_commune:18000,
        departement:18000,
    },
    {
        str:"4)Sur pirogue(a) - par pirogue",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"5)Par chemin de fer(a)",
        lbv_pog:18000,
        autre_commune:18000,
        departement:18000,
    },
    {
        str:"5)Par chemin de fer(a) - par porteur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"6)A pied ou avec des animaux porteurs(a)",
        lbv_pog:18000,
        autre_commune:18000,
        departement:12000,
    },
    {
        str:"6)A pied ou avec animaux porteurs(a) - par animal porteur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"6)A pied ou avec animaux porteurs(a) - par porteur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"7)Vendant des objets de curiosité(a)",
        lbv_pog:18000,
        autre_commune:18000,
        departement:18000,
    },
    {
        str:"7)Vendant des objets de curiosité(a) - par animal porteur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"7)Vendant des objets de curiosité(a) - par porteur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"(a)la patente n'est valable que dans la commune ou le département",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Marchandises(Comissionnaire en)",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Marchands casseur(Epaves de véhicules)",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Maroquinier(voir Cordonnier)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Masseur, masseuse(voir Coiffeur pour dames pour les TV",
        lbv_pog:60000,
        autre_commune:60000,
        departement:50000,
    },
    {
        str:"Matériel aérien(Location de)",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Matériel aérien(Location de) - par appareil",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Matériel aérien(Location, vente et exploitation)",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Matériel aérien(Location, vente et exploitation) - par cheval-vapeur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Matériel ferroviaire(Location de)",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Matériel et mobiliaire d'occasion",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
]