module.exports = [
    {
        str: "Boucher charcutier",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Boucher charcutier - importateur ayant boutique ou installation fixe dans un centre",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Boucher charpantier - ayant boutique ou installation fixe dans un centre et n'important pas",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Boucher charpantier - vendant dans un centre sans boutique ni installation fixe",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Boucher charpantier - vendant hors d'un centre sans boutique ni installation fixe",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str: "Boulanger",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Boulanger - employant des moyens mécaniques",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Boulanger - sans moyens mécaniques employant 5 personnes",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str: "Boulanger - sans moyens mécaniques employant moins de 5 personnes",
        lbv_pog:24000,
        autre_commune:24000,
        departement:18000,
    },
    {
        str: "Bowling(Exploitant un)",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str: "Bowling(Exploitant un) - par piste",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str: "Briqueterie",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Briqueterie - par CV de matériel utilisé, non compris les véhicules",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Briqueterie - par personne employée",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Briqueterie - par personne employée en sus de 10",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Brocanteur",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str: "Bureau d 'études",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Bureau d'études - employant plus d'une personne",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Bureau d'études - employant 1 ou 2 personne",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Bureau d'études - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Café titulaire d'une licence de 1ère classe",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Café titulaire d'une licence de 1ère classe - faisant dancing",
        lbv_pog:260000,
        autre_commune:130000,
        departement:95000,
    },
    {
        str: "Café titulaire d'une licence de 1ère classe - ne faisant pas dancing",
        lbv_pog:160000,
        autre_commune:80000,
        departement:65000,
    },
    {
        str: "Café-restaurant titulaire d'une licence de 1ère classe",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Café-restaurant titulaire d'une licence de 1ère classe - faisant dancing",
        lbv_pog:290000,
        autre_commune:145000,
        departement:110000,
    },
    {
        str: "Café-restaurant titulaire d'une licence de 1ère classe - ne faisant pas dancing",
        lbv_pog:200000,
        autre_commune:110000,
        departement:85000,
    },
    {
        str: "Carrières(Exploitant de)",
        lbv_pog:70000,
        autre_commune:70000,
        departement:70000,
    },
    {
        str: "Carrières(Exploitant de) - par cheval-vapeur du matériel utilisé(véhicules, moteurs)",
        lbv_pog:70000,
        autre_commune:70000,
        departement:70000,
    },
    {
        str: "Carrières(Exploitant de) - par personne employée",
        lbv_pog:70000,
        autre_commune:70000,
        departement:70000,
    },
    {
        str: "Carrières(Exploitant de) - par personne employée en sus de 20",
        lbv_pog:70000,
        autre_commune:70000,
        departement:70000,
    },
    {
        str: "Casino(Exploitant de)",
        lbv_pog:500000,
        autre_commune:500000,
        departement:500000,
    },
    {
        str: "Cassettes pré-enregistrées(Location de)",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Charbon de bois au petit bétail(Marchand de)",
        lbv_pog:15000,
        autre_commune:15000,
        departement:12000,
    },
    {
        str: "Charcutier",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Charcutier - importateur ayant boutique ou installation fixe dans un centre",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Charcutier - ayant boutique ou installation fixe dans un centre et n'important pas",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Charcutier - vendant dans un centre sans boutique ni installation fixe",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str: "Charcutier - vendant hors d'un centre sans boutique ni installation fixe",
        lbv_pog:15000,
        autre_commune:15000,
        departement:12000,
    },
    {
        str: "Charpentier(voir artisan)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Charpentier",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Charpentier - travaillant seul",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str: "Charpentier - employant 1 à 5 personnes",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
]