module.exports = [ 
    {        
        str: "Photographe  - Importateur avec établissement fixe",        
        lbv_pog: 170000,        
        autre_commune: 170000,        
        departement: 170000,    
    },    
    {        
        str: "Photographe  - Importateur avec établissement fixe",        
        lbv_pog: 170000,        
        autre_commune: 170000,        
        departement: 170000,    
    },    
    {        
        str: "Photographe  - N'important pas avec établissement fixe",        
        lbv_pog: 85000,        
        autre_commune: 85000,        
        departement: 60000,    
    },    
    {        
        str: "Photographe  - Sans établissement fixe",        
        lbv_pog: 24000,        
        autre_commune: 24000,        
        departement: 18000,   
    },    
    {       
        str: "Plat cuisiné à emporté (vente sur la voie publique)",        
        lbv_pog: 75000,        
        autre_commune: 75000,        
        departement: 55000,    
    },    
    /*{        
        str: "Plombier(voir artisan)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },*/    
    {        
        str: "Pompes funèbres(entreprise de) - agglomération de plus de 50.000 habitants",        
        lbv_pog: 270000,        
        autre_commune: 270000,        
        departement: 270000,    
    },    
    {        
        str: "Pompes funèbres(entreprise de) - agglomération de 30.000 à 50.000 habitants",        
        lbv_pog: 200000,        
        autre_commune:200000,        
        departement:200000,    
    },    
    {        
        str: "Pompes funèbres(entreprise de) - agglomération de 10.000 à 30.000 habitants",        
        lbv_pog:170000,        
        autre_commune:170000,        
        departement:170000,    
    },    
    {        
        str: "Pompes funèbres(entreprise de) - agglomération de moins de 10.000 habitants",        
        lbv_pog:110000,        
        autre_commune:110000,        
        departement:110000,    
    },    
    {        
        str: "Produit du cru(voir acheteur ou vendeur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,    
    },    
    {        
        str:"Prospection(entreprise)",        
        lbv_pog:200000,        
        autre_commune:200000,        
        departement:200000,    
    },    
    {        
        str: "Remorquage(entreprise de)",        
        lbv_pog:100000,        
        autre_commune:100000,        
        departement:80000,    
    },    
    {        
        str:"Remorquage(entreprise de) - par personne employée",
        lbv_pog:0,
        autre_commune:0,
        departement:0,    
    },    
    {        
        str:"Remorquage(entreprise de) - par cheval-vapeur du matériel utilisé",
        lbv_pog:0,
        autre_commune:0,
        departement:0,    
    },    
    {        
        str: "Représentant de commerce",        
        lbv_pog:65000,        
        autre_commune:65000,        
        departement:55000,    
    },    
    {        
        str:"Restaurant(voir Café-restaurant)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,    
    },    
    {        
        str:"Restaurant ambulant(Véhicule et licence de 3 ème classe",        
        lbv_pog:85000,        
        autre_commune:85000,        
        departement:85000,    
    },    
    {        
        str:"Restaurant titulaire d'une licence de 3 ème classe",        
        lbv_pog:65000,        
        autre_commune:65000,        
        departement:55000,    
    },    
    {        
        str:"Scierie mécanique(voir Atelier)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,    
    },    
    {        
        str:"Soins médicaux(Exercice ambulant de)",        
        lbv_pog:65000,        
        autre_commune:30000,        
        departement:30000,    
    },    
    {        
        str:"Station émettrice de radio ou télévision",        
        lbv_pog:270000,         
        autre_commune:270000,        
        departement:270000,    
    },    
    {        
        str:"Station service d'essence",        
        lbv_pog:65000,        
        autre_commune:65000,        
        departement:55000,    
    },    
    {        
        str:"Syndic de faillite",        
        lbv_pog:65000,        
        autre_commune:65000,        
        departement:55000,    
    },    
    {        
        str:"Tailleur ayant boutique",        
        lbv_pog:40000,        
        autre_commune:40000,        
        departement:30000,    
    },    
    {        
        str:"Tailleur ayant boutique - par machine",
        lbv_pog:40000,
        autre_commune:40000,
        departement:30000,        
    },    
    {        
        str:"Tailleur ayant boutique - par machine en sus de 3",
        lbv_pog:40000,
        autre_commune:40000,
        departement:30000,          
    },    
    {        
        str:"Tailleur ayant boutique - par personne employée",
        lbv_pog:40000,
        autre_commune:40000,
        departement:30000,          
    },    
    {        
        str:"Tailleur sans boutique",        
        lbv_pog:15000,        
        autre_commune:15000,        
        departement:12000,    
    },    
    {        
        str:"Tailleur sans boutique - par machine",
        lbv_pog:15000,        
        autre_commune:15000,        
        departement:12000,          
    },    
    {        
        str:"Tailleur sans boutique - par machine en sus de 3",
        lbv_pog:15000,        
        autre_commune:15000,        
        departement:12000,     
    },    
   /* {        
        str:"Tanneur(voir artisan)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,  
    },*/
];