module.exports = [
    {
        str: "Acheteur de cacao, sans établissement fixe(patente établie par commune ou par département)",
        lbv_pog:60000,
        autre_commune:60000,
        departement:60000,
    },
    {
        str: "Acheteur de produits du cru, sans établissement fixe(patente établie par commune ou par département)",
        lbv_pog:60000,
        autre_commune:60000,
        departement:60000,
    },
    {
        str: "Acconage fluvial(Entreprise de)",
        lbv_pog:100000,
        autre_commune:100000,
        departement:80000,
    },
    {
        str: "Acconage fluvial(Entreprise de) - par personne employée",
        lbv_pog:100000,
        autre_commune:100000,
        departement:80000,
    },
    {
        str: "Acconage fluvial(Entreprise de) - par cheval vapeur du matériel utilisé",
        lbv_pog:100000,
        autre_commune:100000,
        departement:80000,
    },
    {
        str: "Acconage fluvial(Entreprise de) - par tonne métrique des barges, chalands, embarcations utilisées",
        lbv_pog:100000,
        autre_commune:100000,
        departement:80000,
    },
    {
        str: "Acconage maritime(Entreprise de)",
        lbv_pog:170000,
        autre_commune:170000,
        departement:100000,
    },
    {
        str: "Acconage maritime(Entreprise de) - par personne employée",
        lbv_pog:170000,
        autre_commune:170000,
        departement:100000,
    },
    {
        str: "Acconage maritime(Entreprise de) - par cheval vapeur du matériel utilisé",
        lbv_pog:170000,
        autre_commune:170000,
        departement:100000,
    },
    {
        str: "Acconage maritime(Entreprise de) - par tonne métrique de barges, chalands, embarcations utilisées",
        lbv_pog:170000,
        autre_commune:170000,
        departement:1000000,
    },
    {
        str: "Affaires(Agent d')",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Affaires(Agent d') - employant plus d'une personne",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Affaires(Agent d') - employant une personne",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Affaires(Agent d') - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Agence immobilière",
        lbv_pog:150000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Agence de publicité",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Agence de publicité - employant plus d'une personne",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Agence de publicité - employant une personne",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Agence de publicité - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Agréeurs en bois",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str: "Appareils à jeux(Location de)",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Appareils à jeux(Location de) - par appareil",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Architecte ou Bureau d'études(Tenant un)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Architecte ou Bureau d'études(Tenant un) - employant plus de 2 personnes",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Architecte ou Bureau d'études(Tenant un) - employant 1 ou 2 personnes",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Architecte ou Bureau d'études(Tenant un) - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Armateur",
        lbv_pog:100000,
        autre_commune:100000,
        departement:85000,
    },
    {
        str: "Armateur - par tonneau de jauge nette des bateaux et barges",
        lbv_pog:100000,
        autre_commune:100000,
        departement:85000,
    },
    {
        str: "Armateur - par cheval-vapeur des remorqueurs mis à la disposition des tiers moyennant rétribution",
        lbv_pog:100000,
        autre_commune:100000,
        departement:85000,
    },

]