module.exports = [
    {
        str: "Armement à la pêche",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Armement à la pêche - flotte de + de 200 tonneaux de jauge brute par port d'attache",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str: "Armement à la pêche - flotte de 100 à 200 tonneaux de jauge brute par port d'attache",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str: "Armement à la pêche - flotte de 50 à 100 tonneaux de jauge brute par port d'attache",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Armement à la pêche - flotte de 10 à 50 tonneaux de jauge brute par port d'attache",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Artisan(charpentier, couvreur, écailliste, voirier, maçon, menuisier, peintre en bâtiment, plombier, teinturier, etc)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Artisan(charpentier, couvreur, écailliste, voirier, maçon, menuisier, peintre en bâtiment, plombier, teinturier, etc) - travaillant seul",
        lbv_pog:40000,
        autre_commune:40000,
        departement:35000,
    },
    {
        str: "Artisan(charpentier, couvreur, écailliste, voirier, maçon, menuisier, peintre en bâtiment, plombier, teinturier, etc) - employant 1 à 5 personnes",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str: "Artisan(charpentier, couvreur, écailliste, voirier, maçon, menuisier, peintre en bâtiment, plombier, teinturier, etc) - au-dessus de 5 personnes: voir Zntrepreneur de travaux ou exploitant un atelier",
        lbv_pog:65000,
        autre_commune:65000,
        departement:55000,
    },
    {
        str: "Assurances(Agent d')",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Assurances(Agent d') - employant plus d'une personne",
        lbv_pog:200000,
        autre_commune:200000,
        departement:200000,
    },
    {
        str: "Assurances(Agent d') - employant une personne",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Assurances(Agent d') - travaillant seul",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Assurances non mutuelles(Compagnie de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str: "Assurances non mutuelles(Compagnie de) - avec un agent général occupant plus d'un employé",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str: "Assurances non mutuelles(Compagnie de) - avec un agent général occupant un employé",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Assurances non mutuelles(Compagnie de) -  avec un agent général travaillant seul",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str: "Atelier(Exploitant un)",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Atelier(Exploitant un) - par CV de matériel utilisé, non compris les véhicules",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Atelier(Exploitant un) - par personne employée",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Atelier(Exploitant un) - par personne employée en sus de 10",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Atelier mécanographie",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str: "Auto-école(Exploitant une)",
        lbv_pog:70000,
        autre_commune:70000,
        departement:55000,
    },
    {
        str: "Auto-école(Exploitant une) - par véhicule utilisé",
        lbv_pog:70000,
        autre_commune:70000,
        departement:55000,
    },
    {
        str: "Avion",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str: "Avitaillement maritime(Entreprise de)",
        lbv_pog:100000,
        autre_commune:100000,
        departement:100000,
    },
    {
        str: "Avitaillement maritime(Entreprise de) - par bateau",
        lbv_pog:100000,
        autre_commune:100000,
        departement:100000,
    },
]