module.exports = [
    {
        str:"Taxi(Exploitant individuel)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Taxi(Exploitant individuel) - par taxi et par an(5 passagers maximum)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Taxibus urbain(Exploitant individuel)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Taxibus urbain(Exploitant individuel) - par taxi-bus et par an (6 à 10 passagers)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Taxibus urbain(Exploitant individuel) - par taxi-bus et par an ( plus de 10 passagers)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Télécommunications(Entreprise de)",
        lbv_pog:270000,
        autre_commune:270000,
        departement:270000,
    },
    {
        str:"Téléphonie mobile(Entreprise de)",
        lbv_pog:270000,
        autre_commune:270000,
        departement:170000,
    },
    {
        str:"Téléboutique",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Téléboutique - 1 à 3 boxes, par boxe",
        lbv_pog:110000,
        autre_commune:110000,
        departement:80000,
    },
    {
        str:"Téléboutique - plus de 3 boxes",
        lbv_pog:110000,
        autre_commune:110000,
        departement:80000,
    },
    {
        str:"Tradipraticien",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Tradipraticien - exploitant en clinique avec lit",
        lbv_pog:0,
        autre_commune:65000,
        departement:60000,
    },
    {
        str:"Tradipraticien - exploitant en clinique sans lit",
        lbv_pog:0,
        autre_commune:45000,
        departement:40000,
    },
    {
        str:"Traiteur",
        lbv_pog:110000,
        autre_commune:110000,
        departement:110000,
    },
    {
        str:"Transfert d'argent",
        lbv_pog:300000,
        autre_commune:300000,
        departement:200000,
    },
    {
        str:"Transitaire",
        lbv_pog:85000,
        autre_commune:85000,
        departement:60000,
    },
    {
        str:"Transport ferroviaire",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transport ferroviaire - établissement principal(siège social)",
        lbv_pog:370000,
        autre_commune:370000,
        departement:370000,
    },
    {
        str:"Transport ferroviaire - établissement secondaire(gare)",
        lbv_pog:170000,
        autre_commune:170000,
        departement:170000,
    },
    {
        str:"Transport ferroviaire - par chevaux vapeur",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transport ferroviaire - par place",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transport terrestres lagunaires et maritimes(Entrepreneur de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transport terrestres lagunaires et maritimes(Entrepreneur de) - de personnes(par place)",
        lbv_pog: 80000,
        autre_commune:80000,
        departement:80000,
    },
    {
        str:"Transport terrestres lagunaires et maritimes(Entrepreneur de) - de marchandises(par tonne)",
        lbv_pog:80000,
        autre_commune:80000,
        departement:60000,
    },
    {
        str:"Transport terrestres par autobus(Entrepreneur individuel de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transport terrestres par autobus(Entrepreneur individuel de) - par autobus et par an",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transport terrestres par autobus(Entrepreneur individuel de) - par place et par an",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transports terrestres par camion(Entrepreneur individuel de)",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transports terrestres par camion(Entrepreneur individuel de) - par camion et par an",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transports terrestres par camion(Entrepreneur individuel de) - par tonne et par an",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
    {
        str:"Transports terrestres par camion(Entrepreneur individuel de) - par camionnettes<<TM>>",
        lbv_pog:0,
        autre_commune:0,
        departement:0,
    },
]